env:
  global:
    - CC_TEST_REPORTER_ID=ccf72b2f2c856a5152cbf8c40af7a4fa18efbc32dcff247e12a72cdecd202112
language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - pytest --cov=api tests/ # or py.test for Python versions 3.5 and below
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  - coveralls
